USE [master]
GO

/****** Object:  Database [Bangazon]    Script Date: 9/5/2017 5:17:59 PM ******/
CREATE DATABASE [Bangazon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bengazon', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Bengazon.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Bengazon_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Bengazon_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Bangazon] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Bangazon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Bangazon] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Bangazon] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Bangazon] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Bangazon] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Bangazon] SET ARITHABORT OFF 
GO

ALTER DATABASE [Bangazon] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Bangazon] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Bangazon] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Bangazon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Bangazon] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Bangazon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Bangazon] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Bangazon] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Bangazon] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Bangazon] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Bangazon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Bangazon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Bangazon] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Bangazon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Bangazon] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Bangazon] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Bangazon] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Bangazon] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Bangazon] SET  MULTI_USER 
GO

ALTER DATABASE [Bangazon] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Bangazon] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Bangazon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Bangazon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Bangazon] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Bangazon] SET QUERY_STORE = OFF
GO

USE [Bangazon]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Bangazon] SET  READ_WRITE 
GO


